---
- name: Deploy db service
  docker_container:
    name: db
    image: "{{ db_image }}"
    volumes:
      - "{{ db_volume }}"
    env:
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_password }}"
      POSTGRES_DB: "{{ db }}"
    exposed_ports:
      - "{{ db_port }}"
    networks:
      - name: net
    restart_policy: always
